import type { NewsArticle, NewsCategory, VideoItem } from "@/types/news"

export const categories: NewsCategory[] = [
  { id: "1", name: "সর্বশেষ", slug: "latest", description: "সর্বশেষ খবর", order: 0 },
  { id: "2", name: "জাতীয়", slug: "national", description: "দেশের খবর", order: 1 },
  { id: "3", name: "রাজনীতি", slug: "politics", description: "রাজনীতি সংক্রান্ত খবর", order: 2 },
  { id: "4", name: "অর্থনীতি-বাণিজ্য", slug: "business", description: "অর্থনীতি ও ব্যবসা", order: 3 },
  { id: "5", name: "আন্তর্জাতিক", slug: "international", description: "বিশ্বের খবর", order: 4 },
  { id: "6", name: "খেলা", slug: "sports", description: "ক্রীড়া সংক্রান্ত খবর", order: 5 },
  { id: "7", name: "বিনোদন", slug: "entertainment", description: "বিনোদন খবর", order: 6 },
  { id: "8", name: "সারাদেশ", slug: "regions", description: "সারাদেশের খবর", order: 7 },
]

export const sampleNews: NewsArticle[] = [

/* ===================== সর্বশেষ (latest) ===================== */
{
  id: "1",
  title: "সারা দেশে তাপমাত্রা কিছুটা কমেছে",
  slug: "temperature-decrease-countrywide",
  description: "আজ সারা দেশে তাপমাত্রা কিছুটা কমেছে।",
  content: "বিস্তারিত আবহাওয়ার খবর।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T08:00:00Z",
  updatedAt: "2026-01-03T08:00:00Z",
  featured: false,
  views: 5200,
  tags: ["আবহাওয়া"],
},
{
  id: "2",
  title: "ঢাকায় যানজট পরিস্থিতির উন্নতি",
  slug: "dhaka-traffic-improvement",
  description: "ঢাকার প্রধান সড়কে যানজট কমেছে।",
  content: "বিস্তারিত ট্রাফিক আপডেট।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T07:30:00Z",
  updatedAt: "2026-01-03T07:30:00Z",
  featured: false,
  views: 4300,
  tags: ["ঢাকা"],
},
{
  id: "3",
  title: "শিক্ষা প্রতিষ্ঠানে আজ ছুটি",
  slug: "education-institution-holiday",
  description: "বিশেষ কারণে আজ শিক্ষা প্রতিষ্ঠানে ছুটি।",
  content: "বিস্তারিত শিক্ষা সংবাদ।",
  image: "/bangladesh-education.jpg",
  thumbnail: "/bangladesh-education.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T07:00:00Z",
  updatedAt: "2026-01-03T07:00:00Z",
  featured: false,
  views: 6800,
  tags: ["শিক্ষা"],
},
{
  id: "4",
  title: "ডিজিটাল সেবায় নতুন আপডেট",
  slug: "digital-service-update",
  description: "সরকারি ডিজিটাল সেবায় নতুন ফিচার যুক্ত।",
  content: "বিস্তারিত তথ্য।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T06:30:00Z",
  updatedAt: "2026-01-03T06:30:00Z",
  featured: false,
  views: 3900,
  tags: ["ডিজিটাল"],
},
{
  id: "5",
  title: "রেল যোগাযোগ স্বাভাবিক রয়েছে",
  slug: "rail-communication-normal",
  description: "দেশব্যাপী রেল যোগাযোগ স্বাভাবিক।",
  content: "বিস্তারিত পরিবহন সংবাদ।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T06:00:00Z",
  updatedAt: "2026-01-03T06:00:00Z",
  featured: false,
  views: 3100,
  tags: ["রেল"],
},
{
  id: "6",
  title: "বাজারে নিত্যপণ্যের দাম স্থিতিশীল",
  slug: "daily-commodity-price-stable",
  description: "নিত্যপণ্যের দামে স্বস্তি।",
  content: "বিস্তারিত বাজার বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T05:30:00Z",
  updatedAt: "2026-01-03T05:30:00Z",
  featured: false,
  views: 4500,
  tags: ["বাজার"],
},

/* ===================== জাতীয় (national) ===================== */
{
  id: "7",
  title: "প্রধানমন্ত্রীর নতুন নির্দেশনা",
  slug: "pm-new-directive",
  description: "জাতীয় উন্নয়ন নিয়ে প্রধানমন্ত্রীর নির্দেশ।",
  content: "বিস্তারিত বক্তব্য।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 11200,
  tags: ["প্রধানমন্ত্রী"],
},
{
  id: "8",
  title: "জাতীয় স্মৃতিসৌধে শ্রদ্ধা নিবেদন",
  slug: "national-memorial-tribute",
  description: "জাতীয় দিবসে শ্রদ্ধা নিবেদন।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 7600,
  tags: ["জাতীয় দিবস"],
},
{
  id: "9",
  title: "নতুন শিক্ষা নীতিমালা অনুমোদন",
  slug: "new-education-policy-approved",
  description: "শিক্ষা খাতে নতুন নীতিমালা।",
  content: "বিস্তারিত নীতিমালা।",
  image: "/bangladesh-education.jpg",
  thumbnail: "/bangladesh-education.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 6900,
  tags: ["শিক্ষা"],
},
{
  id: "10",
  title: "জাতীয় বাজেট বাস্তবায়নে অগ্রগতি",
  slug: "national-budget-progress",
  description: "বাজেট বাস্তবায়নে সন্তোষজনক অগ্রগতি।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 5400,
  tags: ["বাজেট"],
},
{
  id: "11",
  title: "দেশব্যাপী টিকাদান কর্মসূচি জোরদার",
  slug: "nationwide-vaccination-drive",
  description: "স্বাস্থ্য মন্ত্রণালয়ের উদ্যোগ।",
  content: "বিস্তারিত স্বাস্থ্য সংবাদ।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T12:30:00Z",
  updatedAt: "2026-01-02T12:30:00Z",
  featured: false,
  views: 6200,
  tags: ["স্বাস্থ্য"],
},
{
  id: "12",
  title: "জাতীয় সড়ক উন্নয়ন প্রকল্প",
  slug: "national-road-development",
  description: "সড়ক যোগাযোগ উন্নয়নে নতুন প্রকল্প।",
  content: "বিস্তারিত প্রকল্প তথ্য।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T11:00:00Z",
  updatedAt: "2026-01-02T11:00:00Z",
  featured: false,
  views: 5800,
  tags: ["উন্নয়ন"],
},

/* ===================== রাজনীতি (politics) ===================== */
{
  id: "13",
  title: "বিরোধী দলের নতুন কর্মসূচি ঘোষণা",
  slug: "opposition-new-program",
  description: "সরকার বিরোধী আন্দোলনে নতুন কর্মসূচি।",
  content: "বিস্তারিত রাজনৈতিক প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T19:00:00Z",
  updatedAt: "2026-01-02T19:00:00Z",
  featured: true,
  views: 9800,
  tags: ["বিরোধী দল"],
},
{
  id: "14",
  title: "সংসদ অধিবেশনে তীব্র বিতর্ক",
  slug: "parliament-session-debate",
  description: "সংসদে সরকার ও বিরোধীদের তর্ক।",
  content: "বিস্তারিত সংসদ রিপোর্ট।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T17:30:00Z",
  updatedAt: "2026-01-02T17:30:00Z",
  featured: false,
  views: 7400,
  tags: ["সংসদ"],
},
{
  id: "15",
  title: "নির্বাচন কমিশনের বৈঠক অনুষ্ঠিত",
  slug: "election-commission-meeting",
  description: "আসন্ন নির্বাচন নিয়ে আলোচনা।",
  content: "বিস্তারিত ইসি খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 6200,
  tags: ["নির্বাচন"],
},
{
  id: "16",
  title: "রাজনৈতিক দলের সম্মেলন আজ",
  slug: "political-party-conference",
  description: "দলীয় সম্মেলনে গুরুত্বপূর্ণ সিদ্ধান্ত।",
  content: "বিস্তারিত খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T13:00:00Z",
  updatedAt: "2026-01-02T13:00:00Z",
  featured: false,
  views: 5600,
  tags: ["দলীয় সম্মেলন"],
},
{
  id: "17",
  title: "রাজনৈতিক সহিংসতা নিয়ে উদ্বেগ",
  slug: "political-violence-concern",
  description: "সহিংসতা এড়াতে প্রশাসনের তৎপরতা।",
  content: "বিস্তারিত আইনশৃঙ্খলা সংবাদ।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T11:30:00Z",
  updatedAt: "2026-01-02T11:30:00Z",
  featured: false,
  views: 5900,
  tags: ["সহিংসতা"],
},
{
  id: "18",
  title: "রাজনৈতিক সংলাপের আহ্বান",
  slug: "call-for-political-dialogue",
  description: "সংলাপে বসার আহ্বান জানিয়েছেন নেতারা।",
  content: "বিস্তারিত রাজনৈতিক বিশ্লেষণ।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T10:00:00Z",
  updatedAt: "2026-01-02T10:00:00Z",
  featured: false,
  views: 5100,
  tags: ["সংলাপ"],
},

/* ===================== অর্থনীতি-বাণিজ্য (business) ===================== */
{
  id: "19",
  title: "ডলার বাজারে স্থিতিশীলতা",
  slug: "dollar-market-stable",
  description: "ডলার দর স্থিতিশীল রয়েছে।",
  content: "বিস্তারিত অর্থনৈতিক বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T19:30:00Z",
  updatedAt: "2026-01-02T19:30:00Z",
  featured: true,
  views: 8800,
  tags: ["ডলার"],
},
{
  id: "20",
  title: "শেয়ারবাজারে সূচকের উত্থান",
  slug: "stock-market-index-up",
  description: "আজ শেয়ারবাজারে ইতিবাচক প্রবণতা।",
  content: "বিস্তারিত শেয়ারবাজার খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T17:00:00Z",
  updatedAt: "2026-01-02T17:00:00Z",
  featured: false,
  views: 7600,
  tags: ["শেয়ারবাজার"],
},
{
  id: "21",
  title: "রপ্তানি আয়ে প্রবৃদ্ধি",
  slug: "export-income-growth",
  description: "রপ্তানি খাতে ভালো খবর।",
  content: "বিস্তারিত বাণিজ্য প্রতিবেদন।",
  image: "/bangladesh-export.jpg",
  thumbnail: "/bangladesh-export.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 9100,
  tags: ["রপ্তানি"],
},
{
  id: "22",
  title: "ব্যাংক খাতে নতুন নির্দেশনা",
  slug: "banking-sector-guideline",
  description: "ব্যাংকিং খাতে নতুন নিয়ম।",
  content: "বিস্তারিত ব্যাংকিং সংবাদ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T13:30:00Z",
  updatedAt: "2026-01-02T13:30:00Z",
  featured: false,
  views: 6400,
  tags: ["ব্যাংক"],
},
{
  id: "23",
  title: "জ্বালানি তেলের দামে পরিবর্তন",
  slug: "fuel-price-change",
  description: "জ্বালানি তেলের নতুন দাম ঘোষণা।",
  content: "বিস্তারিত জ্বালানি খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T11:00:00Z",
  updatedAt: "2026-01-02T11:00:00Z",
  featured: false,
  views: 10200,
  tags: ["জ্বালানি"],
},
{
  id: "24",
  title: "ক্ষুদ্র উদ্যোক্তাদের জন্য প্রণোদনা",
  slug: "small-business-incentive",
  description: "এসএমই খাতে সরকারি সহায়তা।",
  content: "বিস্তারিত প্রণোদনা তথ্য।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T09:30:00Z",
  updatedAt: "2026-01-02T09:30:00Z",
  featured: false,
  views: 5800,
  tags: ["এসএমই"],
},

/* ===================== আন্তর্জাতিক (international) ===================== */
{
  id: "25",
  title: "মধ্যপ্রাচ্যে নতুন শান্তি আলোচনা",
  slug: "middle-east-peace-talks",
  description: "শান্তি আলোচনায় অগ্রগতি।",
  content: "বিস্তারিত আন্তর্জাতিক খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 8300,
  tags: ["মধ্যপ্রাচ্য"],
},
{
  id: "26",
  title: "যুক্তরাষ্ট্রে অর্থনৈতিক অগ্রগতি",
  slug: "usa-economic-progress",
  description: "মার্কিন অর্থনীতিতে ইতিবাচক ইঙ্গিত।",
  content: "বিস্তারিত বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 6100,
  tags: ["যুক্তরাষ্ট্র"],
},
{
  id: "27",
  title: "ইউরোপে তীব্র শীত",
  slug: "europe-severe-winter",
  description: "শীতে বিপর্যস্ত ইউরোপ।",
  content: "বিস্তারিত আবহাওয়া প্রতিবেদন।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 7200,
  tags: ["ইউরোপ"],
},
{
  id: "28",
  title: "জাতিসংঘে গুরুত্বপূর্ণ প্রস্তাব",
  slug: "un-important-resolution",
  description: "জাতিসংঘে নতুন প্রস্তাব গৃহীত।",
  content: "বিস্তারিত আন্তর্জাতিক রাজনীতি।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 5600,
  tags: ["জাতিসংঘ"],
},
{
  id: "29",
  title: "চীনের নতুন প্রযুক্তি উদ্ভাবন",
  slug: "china-new-technology",
  description: "প্রযুক্তিতে চীনের অগ্রগতি।",
  content: "বিস্তারিত প্রযুক্তি খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T12:00:00Z",
  updatedAt: "2026-01-02T12:00:00Z",
  featured: false,
  views: 6700,
  tags: ["প্রযুক্তি"],
},
{
  id: "30",
  title: "ভারতে নির্বাচনী প্রস্তুতি",
  slug: "india-election-preparation",
  description: "নির্বাচনের প্রস্তুতিতে ব্যস্ত ভারত।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T10:30:00Z",
  updatedAt: "2026-01-02T10:30:00Z",
  featured: false,
  views: 7400,
  tags: ["ভারত"],
},

/* ===================== খেলা (sports) ===================== */
{
  id: "31",
  title: "বাংলাদেশ ক্রিকেট দলের সিরিজ জয়",
  slug: "bangladesh-cricket-series-victory",
  description: "সিরিজ জয়ে উচ্ছ্বসিত ক্রিকেটপ্রেমীরা।",
  content: "ম্যাচ রিপোর্ট ও স্কোরকার্ড।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T21:00:00Z",
  updatedAt: "2026-01-02T21:00:00Z",
  featured: true,
  views: 19500,
  tags: ["ক্রিকেট", "বাংলাদেশ"],
},
{
  id: "32",
  title: "ফুটবল দলের অনুশীলন জোরদার",
  slug: "bangladesh-football-training",
  description: "আন্তর্জাতিক ম্যাচ সামনে রেখে প্রস্তুতি।",
  content: "অনুশীলনের বিস্তারিত খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T19:00:00Z",
  updatedAt: "2026-01-02T19:00:00Z",
  featured: false,
  views: 8400,
  tags: ["ফুটবল"],
},
{
  id: "33",
  title: "বিপিএলে নতুন রেকর্ড",
  slug: "bpl-new-record",
  description: "বিপিএলে রানের নতুন রেকর্ড।",
  content: "ম্যাচ বিশ্লেষণ।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T17:00:00Z",
  updatedAt: "2026-01-02T17:00:00Z",
  featured: false,
  views: 12300,
  tags: ["বিপিএল"],
},
{
  id: "34",
  title: "এশিয়ান গেমসে বাংলাদেশের প্রস্তুতি",
  slug: "asian-games-bangladesh-preparation",
  description: "এশিয়ান গেমসকে সামনে রেখে প্রস্তুতি।",
  content: "খেলোয়াড়দের অনুশীলনের খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T15:30:00Z",
  updatedAt: "2026-01-02T15:30:00Z",
  featured: false,
  views: 6900,
  tags: ["এশিয়ান গেমস"],
},
{
  id: "35",
  title: "নারী ক্রিকেট দলের জয়",
  slug: "bangladesh-women-cricket-win",
  description: "নারী ক্রিকেটে বাংলাদেশের সাফল্য।",
  content: "ম্যাচের বিস্তারিত।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 8800,
  tags: ["নারী ক্রিকেট"],
},
{
  id: "36",
  title: "হকিতে জাতীয় দলের প্রস্তুতি",
  slug: "bangladesh-hockey-team-preparation",
  description: "হকি দলের প্রস্তুতি ক্যাম্প শুরু।",
  content: "দলের প্রস্তুতির খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T12:30:00Z",
  updatedAt: "2026-01-02T12:30:00Z",
  featured: false,
  views: 5400,
  tags: ["হকি"],
},

/* ===================== বিনোদন (entertainment) ===================== */
{
  id: "37",
  title: "নতুন বাংলা সিনেমা মুক্তি পাচ্ছে",
  slug: "new-bangla-movie-release-week",
  description: "এই সপ্তাহে প্রেক্ষাগৃহে আসছে নতুন ছবি।",
  content: "চলচ্চিত্রের কাহিনি ও অভিনয়।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 10200,
  tags: ["চলচ্চিত্র"],
},
{
  id: "38",
  title: "ওটিটি প্ল্যাটফর্মে নতুন সিরিজ",
  slug: "new-ott-web-series",
  description: "ওটিটিতে নতুন ওয়েব সিরিজ মুক্তি।",
  content: "সিরিজের গল্প ও অভিনেতা।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T18:30:00Z",
  updatedAt: "2026-01-02T18:30:00Z",
  featured: false,
  views: 8600,
  tags: ["ওটিটি"],
},
{
  id: "39",
  title: "সংগীত জগতে নতুন অ্যালবাম",
  slug: "new-music-album-release",
  description: "জনপ্রিয় শিল্পীর নতুন অ্যালবাম।",
  content: "অ্যালবামের গান ও প্রতিক্রিয়া।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T16:00:00Z",
  updatedAt: "2026-01-02T16:00:00Z",
  featured: false,
  views: 7400,
  tags: ["সংগীত"],
},
{
  id: "40",
  title: "নাটকের মঞ্চে নতুন প্রযোজনা",
  slug: "new-stage-drama",
  description: "মঞ্চে নতুন নাটকের উদ্বোধন।",
  content: "নাটকের কাহিনি ও শিল্পী।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T14:30:00Z",
  updatedAt: "2026-01-02T14:30:00Z",
  featured: false,
  views: 5300,
  tags: ["নাটক"],
},
{
  id: "41",
  title: "টেলিভিশন শোতে নতুন বিচারক",
  slug: "tv-show-new-judge",
  description: "জনপ্রিয় শোতে নতুন বিচারক যুক্ত।",
  content: "শো সংক্রান্ত বিস্তারিত।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T13:00:00Z",
  updatedAt: "2026-01-02T13:00:00Z",
  featured: false,
  views: 6100,
  tags: ["টিভি শো"],
},
{
  id: "42",
  title: "সেলিব্রিটিদের সামাজিক উদ্যোগ",
  slug: "celebrity-social-initiative",
  description: "মানবিক কাজে এগিয়ে এলেন তারকারা।",
  content: "সামাজিক কার্যক্রমের খবর।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T11:30:00Z",
  updatedAt: "2026-01-02T11:30:00Z",
  featured: false,
  views: 5800,
  tags: ["সেলিব্রিটি"],
},

/* ===================== সারাদেশ (regions) ===================== */
{
  id: "43",
  title: "চট্টগ্রামে নতুন উন্নয়ন প্রকল্প শুরু",
  slug: "chittagong-new-development-project",
  description: "চট্টগ্রামে বড় উন্নয়ন প্রকল্পের সূচনা।",
  content: "প্রকল্পের বিস্তারিত তথ্য।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T20:30:00Z",
  updatedAt: "2026-01-02T20:30:00Z",
  featured: true,
  views: 9200,
  tags: ["চট্টগ্রাম"],
},
{
  id: "44",
  title: "রাজশাহীতে কৃষি উৎপাদন বৃদ্ধি",
  slug: "rajshahi-agriculture-growth",
  description: "কৃষিতে রাজশাহীর সাফল্য।",
  content: "কৃষি খাতের প্রতিবেদন।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 6400,
  tags: ["রাজশাহী"],
},
{
  id: "45",
  title: "সিলেটে পর্যটনের নতুন সম্ভাবনা",
  slug: "sylhet-tourism-potential",
  description: "পর্যটনে সম্ভাবনাময় সিলেট।",
  content: "পর্যটন উন্নয়নের খবর।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 7100,
  tags: ["সিলেট"],
},
{
  id: "46",
  title: "খুলনায় নদী খনন প্রকল্প",
  slug: "khulna-river-dredging-project",
  description: "নদী খননে খুলনায় নতুন উদ্যোগ।",
  content: "প্রকল্পের বিস্তারিত।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 5900,
  tags: ["খুলনা"],
},
{
  id: "47",
  title: "বরিশালে বন্যা পরিস্থিতির উন্নতি",
  slug: "barisal-flood-situation-improved",
  description: "বরিশালে বন্যা পরিস্থিতি স্বাভাবিকের পথে।",
  content: "বিস্তারিত পরিস্থিতি প্রতিবেদন।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T13:30:00Z",
  updatedAt: "2026-01-02T13:30:00Z",
  featured: false,
  views: 8200,
  tags: ["বরিশাল"],
},
{
  id: "48",
  title: "রংপুরে নতুন শিল্প অঞ্চল",
  slug: "rangpur-new-industrial-zone",
  description: "রংপুরে শিল্পায়নের নতুন দিগন্ত।",
  content: "শিল্প অঞ্চলের বিস্তারিত।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T12:00:00Z",
  updatedAt: "2026-01-02T12:00:00Z",
  featured: false,
  views: 6700,
  tags: ["রংপুর"],
},
];


export const sampleVideos: VideoItem[] = [
  {
    id: "1",
    title: "জক্ষম বক্তৃতার অভিযোগ - মুখ খুলেলেন জাবি শিক্ষক",
    thumbnail: "/press-conference-dhaka.jpg",
    videoUrl: "https://example.com/video1",
    description: "গুরুত্বপূর্ণ সাংবাদিক সম্মেলনের ভিডিও রিপোর্ট।",
    duration: "5:23",
    publishedAt: "2026-01-03T14:00:00Z",
    views: 24560,
  },
  {
    id: "2",
    title: '"সবাইকে তো ইঞ্চা থাকে প্রতিটা ফরম্যাট খেলার"',
    thumbnail: "/cricket-interview.jpg",
    videoUrl: "https://example.com/video2",
    description: "ক্রিকেট তারকার একচেটিয়া সাক্ষাৎকার।",
    duration: "4:15",
    publishedAt: "2026-01-03T13:30:00Z",
    views: 18900,
  },
  {
    id: "3",
    title: "সীমানে নীতির রাষ্ট্র দিয়ে পবিত্র উচ্চাকাঙ্ক্ষা",
    thumbnail: "/government-announcement.jpg",
    videoUrl: "https://example.com/video3",
    description: "সরকারি ঘোষণা এবং বিবৃতি।",
    duration: "3:45",
    publishedAt: "2026-01-03T12:00:00Z",
    views: 12340,
  },
  {
    id: "4",
    title: "সীমান নেতৃত্ব বিষয় এ ভিডিও প্রতিক্রিয়া",
    thumbnail: "/political-news.jpg",
    videoUrl: "https://example.com/video4",
    description: "রাজনৈতিক নেতাদের ভিডিও প্রতিক্রিয়া।",
    duration: "6:10",
    publishedAt: "2026-01-02T15:45:00Z",
    views: 15670,
  },
  {
    id: "5",
    title: "দুর্নীতি রোধে ব্যবস্থা নেওয়ার প্রতিশ্রুতি",
    thumbnail: "/anti-corruption.jpg",
    videoUrl: "https://example.com/video5",
    description: "দুর্নীতি বিরোধী অভিযান সম্পর্কে খবর।",
    duration: "4:30",
    publishedAt: "2026-01-02T14:20:00Z",
    views: 21450,
  },
  {
    id: "6",
    title: "প্রাকৃতিক দুর্যোগ প্রতিরোধে নতুন উদ্যোগ",
    thumbnail: "/disaster-management.jpg",
    videoUrl: "https://example.com/video6",
    description: "প্রাকৃতিক দুর্যোগ মোকাবেলার উপায়।",
    duration: "5:50",
    publishedAt: "2026-01-02T13:10:00Z",
    views: 8920,
  },
]
