import type { NewsArticle, NewsCategory, VideoItem } from "@/types/news"

export const categories: NewsCategory[] = [
  { id: "1", name: "সর্বশেষ", slug: "latest", description: "সর্বশেষ খবর", order: 0 },
  { id: "2", name: "জাতীয়", slug: "national", description: "দেশের খবর", order: 1 },
  { id: "3", name: "রাজনীতি", slug: "politics", description: "রাজনীতি সংক্রান্ত খবর", order: 2 },
  { id: "4", name: "অর্থনীতি-বাণিজ্য", slug: "business", description: "অর্থনীতি ও ব্যবসা", order: 3 },
  { id: "5", name: "আন্তর্জাতিক", slug: "international", description: "বিশ্বের খবর", order: 4 },
  { id: "6", name: "খেলা", slug: "sports", description: "ক্রীড়া সংক্রান্ত খবর", order: 5 },
  { id: "7", name: "বিনোদন", slug: "entertainment", description: "বিনোদন খবর", order: 6 },
  { id: "8", name: "সারাদেশ", slug: "regions", description: "সারাদেশের খবর", order: 7 },
]

export const sampleNews: NewsArticle[] = [

/* ===================== সর্বশেষ (latest) ===================== */
{
  id: "1",
  title: "সারা দেশে তাপমাত্রা কিছুটা কমেছে",
  slug: "temperature-decrease-countrywide",
  description: "দেশের উত্তরাঞ্চলসহ সারাদেশে শীতের তীব্রতা কিছুটা কমলেও রংপুর অঞ্চলে এখনও হাড়কাঁপানো ঠাণ্ডা বিরাজ করছে। রংপুর মেডিকেলে শীতজনিত রোগে আক্রান্ত হয়ে ইতোমধ্যে ১৬ জনের মৃত্যু হয়েছে এবং ৭ শতাধিক রোগী চিকিৎসাধীন রয়েছেন। বিশেষজ্ঞদের মতে, হিমালয়ের বরফ শীতল বাতাসের প্রভাবে এই অঞ্চলে পরিস্থিতি আরও কয়েকদিন অব্যাহত থাকতে পারে।",
  content: "বিস্তারিত আবহাওয়ার খবর।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T08:00:00Z",
  updatedAt: "2026-01-03T08:00:00Z",
  featured: false,
  views: 5200,
  tags: ["আবহাওয়া"],
},
{
  id: "2",
  title: "ঢাকায় যানজট পরিস্থিতির উন্নতি",
  slug: "dhaka-traffic-improvement",
  description: "রাজধানী ঢাকার প্রধান প্রধান সড়কে যানজটের পরিস্থিতিতে কিছুটা উন্নতি দেখা গেছে। বিশেষ করে পিক আওয়ারেও আগের তুলনায় গতিশীলতা বেড়েছে। তবে কিছু কিছু স্থানে এখনও যানজটের সমস্যা অব্যাহত রয়েছে বলে জানিয়েছে ট্রাফিক পুলিশ।",
  content: "বিস্তারিত ট্রাফিক আপডেট।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T07:30:00Z",
  updatedAt: "2026-01-03T07:30:00Z",
  featured: false,
  views: 4300,
  tags: ["ঢাকা"],
},
{
  id: "3",
  title: "শিক্ষা প্রতিষ্ঠানে আজ ছুটি",
  slug: "education-institution-holiday",
  description: "তীব্র শৈত্যপ্রবাহের কারণে দেশের বেশিরভাগ শিক্ষা প্রতিষ্ঠানে আজ ছুটি ঘোষণা করা হয়েছে। প্রাথমিক ও মাধ্যমিক পর্যায়ের সব শিক্ষা প্রতিষ্ঠান বন্ধ থাকবে। উচ্চ মাধ্যমিক ও বিশ্ববিদ্যালয় পর্যায়ের প্রতিষ্ঠানগুলো নিজস্ব সিদ্ধান্ত নেবে বলে জানানো হয়েছে।",
  content: "বিস্তারিত শিক্ষা সংবাদ।",
  image: "/bangladesh-education.jpg",
  thumbnail: "/bangladesh-education.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T07:00:00Z",
  updatedAt: "2026-01-03T07:00:00Z",
  featured: false,
  views: 6800,
  tags: ["শিক্ষা"],
},
{
  id: "4",
  title: "ডিজিটাল সেবায় নতুন আপডেট",
  slug: "digital-service-update",
  description: "সরকারি ডিজিটাল সেবা পোর্টালে নতুন ফিচার যুক্ত করা হয়েছে। ব্যবহারকারীরা এখন মোবাইল অ্যাপের মাধ্যমে আরও দ্রুত সেবা নিতে পারবেন। ডিজিটাল নিরাপত্তা ব্যবস্থাও আরও শক্তিশালী করা হয়েছে নতুন আপডেটে।",
  content: "বিস্তারিত তথ্য।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T06:30:00Z",
  updatedAt: "2026-01-03T06:30:00Z",
  featured: false,
  views: 3900,
  tags: ["ডিজিটাল"],
},
{
  id: "5",
  title: "রেল যোগাযোগ স্বাভাবিক রয়েছে",
  slug: "rail-communication-normal",
  description: "দেশব্যাপী রেল যোগাযোগ ব্যবস্থা পুরোপুরি স্বাভাবিক রয়েছে। শৈত্যপ্রবাহের কারণে কোনো ধরনের বাধার সৃষ্টি হয়নি বলেই জানিয়েছে রেলপথ মন্ত্রণালয়। সব ট্রেন যথাসময়ে তাদের গন্তব্যে পৌঁছাচ্ছে এবং যাত্রীসেবাও নিরবচ্ছিন্নভাবে চলছে।",
  content: "বিস্তারিত পরিবহন সংবাদ।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T06:00:00Z",
  updatedAt: "2026-01-03T06:00:00Z",
  featured: false,
  views: 3100,
  tags: ["রেল"],
},
{
  id: "6",
  title: "বাজারে নিত্যপণ্যের দাম স্থিতিশীল",
  slug: "daily-commodity-price-stable",
  description: "দুর্নীতি দমন কমিশনের চেয়ারম্যান ড. মোহাম্মদ আবদুল মোমেন জানিয়েছেন, ২০২৬ সাল গণতন্ত্র উত্তরণের একটি বছর হবে। ত্রয়োদশ জাতীয় সংসদ নির্বাচনের প্রস্তুতিতে হলফনামায় উল্লেখিত প্রার্থীদের সম্পদের বিবরণী পরীক্ষা করা হবে। নির্বাচনী ব্যয় নিয়েও নজরদারি বাড়ানো হবে বলে জানান তিনি।",
  content: "বিস্তারিত বাজার বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "সর্বশেষ",
  categorySlug: "latest",
  author: "ডেস্ক রিপোর্ট",
  publishedAt: "2026-01-03T05:30:00Z",
  updatedAt: "2026-01-03T05:30:00Z",
  featured: false,
  views: 4500,
  tags: ["বাজার"],
},

/* ===================== জাতীয় (national) ===================== */
{
  id: "7",
  title: "প্রধানমন্ত্রীর নতুন নির্দেশনা",
  slug: "pm-new-directive",
  description: "জাতীয় উন্নয়ন ত্বরান্বিত করতে প্রধানমন্ত্রী শেখ হাসিনা নতুন নির্দেশনা দিয়েছেন। বিশেষ করে গ্রামীণ অবকাঠামো উন্নয়ন ও ডিজিটাল বাংলাদেশের রূপকল্প বাস্তবায়নে অধিকতর গতি আনার আহ্বান জানিয়েছেন। সংশ্লিষ্ট মন্ত্রণালয়গুলোকে দ্রুত কার্যক্রম শুরু করারও নির্দেশ দেন তিনি।",
  content: "বিস্তারিত বক্তব্য।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 11200,
  tags: ["প্রধানমন্ত্রী"],
},
{
  id: "8",
  title: "জাতীয় স্মৃতিসৌধে শ্রদ্ধা নিবেদন",
  slug: "national-memorial-tribute",
  description: "আজকের জাতীয় দিবসে রাষ্ট্রপতি, প্রধানমন্ত্রী এবং বিরোধীদলীয় নেতাসহ বিভিন্ন রাজনৈতিক দলের নেতাকর্মীরা জাতীয় স্মৃতিসৌধে ফুলেল শ্রদ্ধা নিবেদন করেন। মুক্তিযুদ্ধে আত্মদানকারী বীর শহীদদের স্মরণে এক মিনিট নীরবতা পালন করা হয় এবং বিশেষ দোয়া মাহফিলের আয়োজন করা হয়।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 7600,
  tags: ["জাতীয় দিবস"],
},
{
  id: "9",
  title: "নতুন শিক্ষা নীতিমালা অনুমোদন",
  slug: "new-education-policy-approved",
  description: "মন্ত্রিসভার বৈঠকে নতুন শিক্ষা নীতিমালা চূড়ান্তভাবে অনুমোদন পেয়েছে। নতুন এই নীতিমালায় কারিগরি ও বৃত্তিমূলক শিক্ষার ওপর বেশি গুরুত্ব দেওয়া হয়েছে। পাশাপাশি প্রাথমিক শিক্ষাকে বাধ্যতামূলক ও অবৈতনিক করার প্রস্তাবও অন্তর্ভুক্ত রয়েছে।",
  content: "বিস্তারিত নীতিমালা।",
  image: "/bangladesh-education.jpg",
  thumbnail: "/bangladesh-education.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 6900,
  tags: ["শিক্ষা"],
},
{
  id: "10",
  title: "জাতীয় বাজেট বাস্তবায়নে অগ্রগতি",
  slug: "national-budget-progress",
  description: "চলতি অর্থবছরের প্রথম ছয় মাসে জাতীয় বাজেটের ৪৫ শতাংশ বাস্তবায়ন হয়েছে বলে অর্থ মন্ত্রণালয়ের প্রতিবেদনে উঠে এসেছে। রাজস্ব আদায়ের ক্ষেত্রেও লক্ষ্যমাত্রার তুলনায় বেশি আদায় হয়েছে। বিশেষ করে কর আদায়ে রেকর্ড অর্জন করেছে জাতীয় রাজস্ব বোর্ড।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 5400,
  tags: ["বাজেট"],
},
{
  id: "11",
  title: "দেশব্যাপী টিকাদান কর্মসূচি জোরদার",
  slug: "nationwide-vaccination-drive",
  description: "স্বাস্থ্য মন্ত্রণালয়ের উদ্যোগে দেশব্যাপী টিকাদান কর্মসূচি জোরদার করা হচ্ছে। বিশেষ করে শিশুদের নিয়মিত টিকাদান কার্যক্রমে শতভাগ কভারেজ নিশ্চিত করতে বিশেষ প্রচারণা চালানো হচ্ছে। প্রত্যন্ত অঞ্চলেও টিকাদান কেন্দ্রের সংখ্যা বাড়ানো হচ্ছে।",
  content: "বিস্তারিত স্বাস্থ্য সংবাদ।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T12:30:00Z",
  updatedAt: "2026-01-02T12:30:00Z",
  featured: false,
  views: 6200,
  tags: ["স্বাস্থ্য"],
},
{
  id: "12",
  title: "জাতীয় সড়ক উন্নয়ন প্রকল্প",
  slug: "national-road-development",
  description: "যোগাযোগ ব্যবস্থার উন্নয়নে নতুন জাতীয় সড়ক উন্নয়ন প্রকল্প হাতে নেওয়া হয়েছে। এই প্রকল্পের আওতায় দেশের ৫০টি গুরুত্বপূর্ণ মহাসড়ক আধুনিকায়ন করা হবে। প্রকল্প বাস্তবায়নে বিশ্বব্যাংক ও এশীয় উন্নয়ন ব্যাংকের আর্থিক সহায়তা পাওয়া যাচ্ছে।",
  content: "বিস্তারিত প্রকল্প তথ্য।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "জাতীয়",
  categorySlug: "national",
  author: "জাতীয় ডেস্ক",
  publishedAt: "2026-01-02T11:00:00Z",
  updatedAt: "2026-01-02T11:00:00Z",
  featured: false,
  views: 5800,
  tags: ["উন্নয়ন"],
},

/* ===================== রাজনীতি (politics) ===================== */
{
  id: "13",
  title: "বিরোধী দলের নতুন কর্মসূচি ঘোষণা",
  slug: "opposition-new-program",
  description: "সরকার বিরোধী আন্দোলনকে ত্বরান্বিত করতে বিরোধী দল নতুন কর্মসূচি ঘোষণা করেছে। আগামী সপ্তাহ থেকে দেশব্যাপী গণসংযোগ ও সমাবেশের আয়োজন করা হবে। দাবি আদায় না হওয়া পর্যন্ত আন্দোলন অব্যাহত রাখার ঘোষণা দিয়েছেন বিরোধী দলীয় নেতারা।",
  content: "বিস্তারিত রাজনৈতিক প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T19:00:00Z",
  updatedAt: "2026-01-02T19:00:00Z",
  featured: true,
  views: 9800,
  tags: ["বিরোধী দল"],
},
{
  id: "14",
  title: "সংসদ অধিবেশনে তীব্র বিতর্ক",
  slug: "parliament-session-debate",
  description: "আজ সংসদ অধিবেশনে বাজেট বরাদ্দ নিয়ে সরকার ও বিরোধী দলীয় সাংসদদের মধ্যে তীব্র বিতর্ক হয়। বিরোধী দলীয় সাংসদরা বিভিন্ন মন্ত্রণালয়ের ব্যয় বৃদ্ধির সমালোচনা করেন। সরকারি দলীয় সাংসদরা উন্নয়ন প্রকল্পের অগ্রগতির কথা তুলে ধরে জবাব দেন।",
  content: "বিস্তারিত সংসদ রিপোর্ট।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T17:30:00Z",
  updatedAt: "2026-01-02T17:30:00Z",
  featured: false,
  views: 7400,
  tags: ["সংসদ"],
},
{
  id: "15",
  title: "নির্বাচন কমিশনের বৈঠক অনুষ্ঠিত",
  slug: "election-commission-meeting",
  description: "আসন্ন উপজেলা নির্বাচন প্রস্তুতি নিয়ে নির্বাচন কমিশনের গুরুত্বপূর্ণ বৈঠক অনুষ্ঠিত হয়েছে। বৈঠকে নির্বাচনী আচরণবিধি, নিরাপত্তা ব্যবস্থা ও ভোটগ্রহণ প্রক্রিয়া নিয়ে বিস্তারিত আলোচনা হয়। নির্বাচন কমিশনাররা পর্যবেক্ষক নিয়োগের প্রক্রিয়া নিয়েও পর্যালোচনা করেন।",
  content: "বিস্তারিত ইসি খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 6200,
  tags: ["নির্বাচন"],
},
{
  id: "16",
  title: "রাজনৈতিক দলের সম্মেলন আজ",
  slug: "political-party-conference",
  description: "দেশের একটি বড় রাজনৈতিক দলের কেন্দ্রীয় সম্মেলন আজ ঢাকায় শুরু হয়েছে। সম্মেলনে নতুন কমিটি গঠন ও দলের ভবিষ্যৎ কর্মপন্থা নির্ধারণ করা হবে। দলীয় সভাপতি তাঁর ভাষণে সাম্প্রতিক রাজনৈতিক পরিস্থিতি ও সরকারের সমালোচনা করেন।",
  content: "বিস্তারিত খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T13:00:00Z",
  updatedAt: "2026-01-02T13:00:00Z",
  featured: false,
  views: 5600,
  tags: ["দলীয় সম্মেলন"],
},
{
  id: "17",
  title: "রাজনৈতিক সহিংসতা নিয়ে উদ্বেগ",
  slug: "political-violence-concern",
  description: "দেশের বিভিন্ন স্থানে রাজনৈতিক সহিংসতা বৃদ্ধি পাওয়ায় আইনশৃঙ্খলা বাহিনী তৎপরতা বাড়িয়েছে। গত এক সপ্তাহে অন্তত পাঁচটি রাজনৈতিক সংঘর্ষের ঘটনা ঘটেছে। প্রশাসন সংঘর্ষ এড়াতে সব রাজনৈতিক দলকে সংযমের আহ্বান জানিয়েছে।",
  content: "বিস্তারিত আইনশৃঙ্খলা সংবাদ।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T11:30:00Z",
  updatedAt: "2026-01-02T11:30:00Z",
  featured: false,
  views: 5900,
  tags: ["সহিংসতা"],
},
{
  id: "18",
  title: "রাজনৈতিক সংলাপের আহ্বান",
  slug: "call-for-political-dialogue",
  description: "দেশের বর্তমান রাজনৈতিক সংকট নিরসনে সংলাপের আহ্বান জানিয়েছেন বিশিষ্ট নাগরিকরা। তারা সরকার ও বিরোধী দলকে সংলাপে বসে সমঝোতার মাধ্যমে সমস্যা সমাধানের অনুরোধ জানান। শিক্ষাবিদ ও সুশীল সমাজের প্রতিনিধিরাও এই আহ্বানে সমর্থন দিয়েছেন।",
  content: "বিস্তারিত রাজনৈতিক বিশ্লেষণ।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "রাজনীতি",
  categorySlug: "politics",
  author: "রাজনীতি ডেস্ক",
  publishedAt: "2026-01-02T10:00:00Z",
  updatedAt: "2026-01-02T10:00:00Z",
  featured: false,
  views: 5100,
  tags: ["সংলাপ"],
},

/* ===================== অর্থনীতি-বাণিজ্য (business) ===================== */
{
  id: "19",
  title: "বাংলাদেশকে জেএফ-১৭ থান্ডার যুদ্ধবিমান সরবরাহে আগ্রহী পাকিস্তান",
  slug: "dollar-market-stable",
  description: "পাকিস্তানের এয়ার চিফ মার্শালের সঙ্গে বাংলাদেশ বিমান বাহিনী প্রধান জেএফ-১৭ থান্ডার যুদ্ধবিমান সংগ্রহের বিষয়ে বৈঠক করেছেন। পাকিস্তান বাংলাদেশকে 'সুপার মুশশাক' প্রশিক্ষণ বিমান সরবরাহের প্রতিশ্রুতি দিয়েছে। দুই দেশের মধ্যে প্রতিরক্ষা খাতে দীর্ঘমেয়াদি কৌশলগত অংশীদারিত্ব গড়ে তোলার সংকল্প ব্যক্ত করা হয়েছে।",
  content: "বিস্তারিত অর্থনৈতিক বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T19:30:00Z",
  updatedAt: "2026-01-02T19:30:00Z",
  featured: true,
  views: 8800,
  tags: ["ডলার"],
},
{
  id: "20",
  title: "শেয়ারবাজারে সূচকের উত্থান. শেয়ারবাজারে সূচকের উত্থান",
  slug: "stock-market-index-up",
  description: "আজ ঢাকা স্টক এক্সচেঞ্জের প্রধান সূচক ৮৫ পয়েন্ট বৃদ্ধি পেয়েছে। ব্যাংকিং ও ইন্স্যুরেন্স সেক্টরের শেয়ার দাম বৃদ্ধিতে এই উন্নতি ঘটেছে। বিনিয়োগকারীদের মধ্যে আস্থা ফিরে আসায় লেনদেনের পরিমাণও বেড়েছে প্রায় ৩০ শতাংশ।",
  content: "বিস্তারিত শেয়ারবাজার খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T17:00:00Z",
  updatedAt: "2026-01-02T17:00:00Z",
  featured: false,
  views: 7600,
  tags: ["শেয়ারবাজার"],
},
{
  id: "21",
  title: "রপ্তানি আয়ে প্রবৃদ্ধি শেয়ারবাজারে সূচকের উত্থান ",
  slug: "export-income-growth",
  description: "চলতি অর্থবছরের প্রথম সাত মাসে রপ্তানি আয়ে ১২ শতাংশ প্রবৃদ্ধি অর্জিত হয়েছে। তৈরি পোশাক খাতে সর্বোচ্চ রপ্তানি আয় হয়েছে, যার পরিমাণ ২৫ বিলিয়ন ডলার ছাড়িয়েছে। নতুন বাজার অনুসন্ধান ও পণ্যের বৈচিত্র্য রপ্তানি বৃদ্ধির প্রধান কারণ বলে জানিয়েছে রপ্তানি উন্নয়ন ব্যুরো।",
  content: "বিস্তারিত বাণিজ্য প্রতিবেদন।",
  image: "/bangladesh-export.jpg",
  thumbnail: "/bangladesh-export.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 9100,
  tags: ["রপ্তানি"],
},
{
  id: "22",
  title: "ব্যাংক খাতে নতুন নির্দেশনা",
  slug: "banking-sector-guideline",
  description: "বাংলাদেশ ব্যাংক ব্যাংকিং খাতে নতুন নির্দেশনা জারি করেছে। নতুন নির্দেশনায় ঋণের মান নিয়ন্ত্রণ ও ডিজিটাল ব্যাংকিং নিরাপত্তা জোরদারের উপর গুরুত্ব দেওয়া হয়েছে। সব ব্যাংককে গ্রাহক সেবার মানোন্নয়নে বিশেষ পদক্ষেপ নেওয়ারও নির্দেশ দেওয়া হয়েছে।",
  content: "বিস্তারিত ব্যাংকিং সংবাদ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T13:30:00Z",
  updatedAt: "2026-01-02T13:30:00Z",
  featured: false,
  views: 6400,
  tags: ["ব্যাংক"],
},
{
  id: "23",
  title: "জ্বালানি তেলের দামে পরিবর্তন",
  slug: "fuel-price-change",
  description: "আন্তর্জাতিক বাজারে জ্বালানি তেলের দাম কমার সুবাদে বাংলাদেশেও পেট্রোল ও ডিজেলের দাম কমিয়ে আনা হয়েছে। নতুন দাম আজ থেকে কার্যকর হবে বলে জানিয়েছে বাংলাদেশ পেট্রোলিয়াম কর্পোরেশন। তবে গ্যাস ও বিদ্যুতের দাম অপরিবর্তিত রাখার সিদ্ধান্ত নেওয়া হয়েছে।",
  content: "বিস্তারিত জ্বালানি খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T11:00:00Z",
  updatedAt: "2026-01-02T11:00:00Z",
  featured: false,
  views: 10200,
  tags: ["জ্বালানি"],
},
{
  id: "24",
  title: "ক্ষুদ্র উদ্যোক্তাদের জন্য প্রণোদনা",
  slug: "small-business-incentive",
  description: "ক্ষুদ্র ও মাঝারি উদ্যোক্তাদের জন্য নতুন প্রণোদনা প্যাকেজ ঘোষণা করেছে সরকার। এই প্যাকেজের আওতায় ৫ শতাংশ সুদে ঋণ প্রদান করা হবে। বিশেষ করে নারী উদ্যোক্তাদের জন্য আলাদা কোটা বরাদ্দ রাখা হয়েছে এবং ঋণ প্রাপ্তির শর্ত শিথিল করা হয়েছে।",
  content: "বিস্তারিত প্রণোদনা তথ্য।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "অর্থনীতি-বাণিজ্য",
  categorySlug: "business",
  author: "অর্থনীতি ডেস্ক",
  publishedAt: "2026-01-02T09:30:00Z",
  updatedAt: "2026-01-02T09:30:00Z",
  featured: false,
  views: 5800,
  tags: ["এসএমই"],
},

/* ===================== আন্তর্জাতিক (international) ===================== */
{
  id: "25",
  title: "মধ্যপ্রাচ্যে নতুন শান্তি আলোচনা",
  slug: "middle-east-peast-talks",
  description: "মধ্যপ্রাচ্যে শান্তি প্রক্রিয়া এগিয়ে নিতে নতুন করে আলোচনা শুরু হয়েছে। জাতিসংঘের মধ্যস্থতায় ইসরাইল ও ফিলিস্তিনি প্রতিনিধিদের মধ্যে গোপন বৈঠক চলছে। আঞ্চলিক শান্তি প্রতিষ্ঠায় সৌদি আরব ও মিসরসহ আরব দেশগুলো সক্রিয় ভূমিকা পালন করছে।",
  content: "বিস্তারিত আন্তর্জাতিক খবর।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 8300,
  tags: ["মধ্যপ্রাচ্য"],
},
{
  id: "26",
  title: "যুক্তরাষ্ট্রে অর্থনৈতিক অগ্রগতি",
  slug: "usa-economic-progress",
  description: "যুক্তরাষ্ট্রের অর্থনীতিতে ইতিবাচক সংকেত পাওয়া যাচ্ছে। চাকরির বাজার শক্তিশালী হওয়ায় বেকারত্বের হার ৩.৫ শতাংশে নেমে এসেছে। ফেডারেল রিজার্ভ সুদের হার স্থিতিশীল রাখার সিদ্ধান্ত নিয়েছে, যা বিনিয়োগকারীদের জন্য ইতিবাচক সংকেত।",
  content: "বিস্তারিত বিশ্লেষণ।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 6100,
  tags: ["যুক্তরাষ্ট্র"],
},
{
  id: "27",
  title: "ইউরোপে তীব্র শীত",
  slug: "europe-severe-winter",
  description: "ইউরোপজুড়ে তীব্র শৈত্যপ্রবাহ বিপর্যস্ত করে তুলেছে জনজীবন। ফ্রান্স, জার্মানি ও পোল্যান্ডে তাপমাত্রা মাইনাস ২০ ডিগ্রি সেলসিয়াসের নিচে নেমে গেছে। বিমান ও ট্রেন চলাচল ব্যাহত হওয়ায় হাজার হাজার যাত্রী অসুবিধার সম্মুখীন হচ্ছেন।",
  content: "বিস্তারিত আবহাওয়া প্রতিবেদন।",
  image: "/bangladesh-weather.jpg",
  thumbnail: "/bangladesh-weather.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 7200,
  tags: ["ইউরোপ"],
},
{
  id: "28",
  title: "জাতিসংঘে গুরুত্বপূর্ণ প্রস্তাব",
  slug: "un-important-resolution",
  description: "জলবায়ু পরিবর্তন মোকাবিলায় জাতিসংঘে একটি গুরুত্বপূর্ণ প্রস্তাব গৃহীত হয়েছে। উন্নয়নশীল দেশগুলোকে জলবায়ু তহবিল থেকে আরও সহায়তা প্রদানের জন্য এই প্রস্তাব গ্রহণ করা হয়েছে। প্রস্তাবটি সর্বসম্মতিক্রমে পাস হয়েছে এবং বাস্তবায়নে দ্রুত পদক্ষেপ নেওয়ার সিদ্ধান্ত হয়েছে।",
  content: "বিস্তারিত আন্তর্জাতিক রাজনীতি।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 5600,
  tags: ["জাতিসংঘ"],
},
{
  id: "29",
  title: "চীনের নতুন প্রযুক্তি উদ্ভাবন",
  slug: "china-new-technology",
  description: "চীনের বিজ্ঞানীরা কৃত্রিম বুদ্ধিমত্তা খাতে নতুন একটি প্রযুক্তি উদ্ভাবন করেছেন। এই প্রযুক্তি চিকিৎসা শাস্ত্রে বিপ্লব ঘটাতে সক্ষম হবে বলে দাবি করা হচ্ছে। নতুন উদ্ভাবিত প্রযুক্তিটি ক্যান্সার শনাক্তকরণে ৯৫ শতাংশ সঠিক ফলাফল দিতে সক্ষম।",
  content: "বিস্তারিত প্রযুক্তি খবর।",
  image: "/bangladesh-economy.jpg",
  thumbnail: "/bangladesh-economy.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T12:00:00Z",
  updatedAt: "2026-01-02T12:00:00Z",
  featured: false,
  views: 6700,
  tags: ["প্রযুক্তি"],
},
{
  id: "30",
  title: "ভারতে নির্বাচনী প্রস্তুতি",
  slug: "india-election-preparation",
  description: "আসন্ন লোকসভা নির্বাচনের প্রস্তুতি হিসেবে ভারতের নির্বাচন কমিশন বিশেষ প্রস্তুতি গ্রহণ করেছে। সারাদেশে ভোটার তালিকা হালনাগাদের কাজ দ্রুত গতিতে এগিয়ে চলছে। নির্বাচনী আচরণবিধি লঙ্ঘনকারীদের বিরুদ্ধে কঠোর ব্যবস্থা নেওয়ারও ঘোষণা দেওয়া হয়েছে।",
  content: "বিস্তারিত প্রতিবেদন।",
  image: "/bangladeshi-political-news.jpg",
  thumbnail: "/bangladeshi-political-news.jpg",
  category: "আন্তর্জাতিক",
  categorySlug: "international",
  author: "আন্তর্জাতিক ডেস্ক",
  publishedAt: "2026-01-02T10:30:00Z",
  updatedAt: "2026-01-02T10:30:00Z",
  featured: false,
  views: 7400,
  tags: ["ভারত"],
},

/* ===================== খেলা (sports) ===================== */
{
  id: "31",
  title: "বাংলাদেশ ক্রিকেট দলের সিরিজ জয়",
  slug: "bangladesh-cricket-series-victory",
  description: "নিউজিল্যান্ডের বিপক্ষে টি-টোয়েন্টি সিরিজ জিতে নিয়েছে বাংলাদেশ ক্রিকেট দল। শেষ ম্যাচে ৭ উইকেটে জয়ী হয়ে ২-১ ব্যবধানে সিরিজ জয় নিশ্চিত করেছে টাইগাররা। লিটন দাসের অসাধারণ শতরানের ইনিংস বাংলাদেশকে জয় এনে দিয়েছে।",
  content: "ম্যাচ রিপোর্ট ও স্কোরকার্ড।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T21:00:00Z",
  updatedAt: "2026-01-02T21:00:00Z",
  featured: true,
  views: 19500,
  tags: ["ক্রিকেট", "বাংলাদেশ"],
},
{
  id: "32",
  title: "ফুটবল দলের অনুশীলন জোরদার",
  slug: "bangladesh-football-training",
  description: "আসন্ন সাফ চ্যাম্পিয়নশিপকে সামনে রেখে বাংলাদেশ ফুটবল দলের অনুশীলন জোরদার করা হয়েছে। স্প্যানিশ কোচের অধীনে দলটি বিশেষ ট্যাকটিক্যাল অনুশীলনে ব্যস্ত সময় পার করছে। আঘাত থেকে ফিরে আসা খেলোয়াড়রাও দলে যোগ দিয়েছেন এবং পুরোদমে অনুশীলন করছেন।",
  content: "অনুশীলনের বিস্তারিত খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T19:00:00Z",
  updatedAt: "2026-01-02T19:00:00Z",
  featured: false,
  views: 8400,
  tags: ["ফুটবল"],
},
{
  id: "33",
  title: "বিপিএলে নতুন রেকর্ড",
  slug: "bpl-new-record",
  description: "বাংলাদেশ প্রিমিয়ার লিগে নতুন রেকর্ড সৃষ্টি করেছেন কুমিল্লা ভিক্টোরিয়ানের ব্যাটসম্যান। এক ইনিংসে ১৫টি ছক্কার মাধ্যমে তিনি বিপিএলের ইতিহাসে সবচেয়ে বেশি ছক্কার রেকর্ড গড়েছেন। তাঁর ১৩৫ রানের ইনিংসে দলটি ২২০ রানের বিশাল সংগ্রহ গড়ে।",
  content: "ম্যাচ বিশ্লেষণ।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T17:00:00Z",
  updatedAt: "2026-01-02T17:00:00Z",
  featured: false,
  views: 12300,
  tags: ["বিপিএল"],
},
{
  id: "34",
  title: "এশিয়ান গেমসে বাংলাদেশের প্রস্তুতি",
  slug: "asian-games-bangladesh-preparation",
  description: "আসন্ন এশিয়ান গেমসে ভালো ফলাফলের জন্য বাংলাদেশের অ্যাথলেটদের প্রস্তুতি জোরদার করা হয়েছে। বিশেষ করে সাঁতার, দাবা ও শুটিং ইভেন্টে মেডেল আশা করছে বাংলাদেশ। ক্রীড়াবিদদের বিদেশে প্রশিক্ষণের জন্য বিশেষ বরাদ্দ দেওয়া হয়েছে।",
  content: "খেলোয়াড়দের অনুশীলনের খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T15:30:00Z",
  updatedAt: "2026-01-02T15:30:00Z",
  featured: false,
  views: 6900,
  tags: ["এশিয়ান গেমস"],
},
{
  id: "35",
  title: "নারী ক্রিকেট দলের জয়",
  slug: "bangladesh-women-cricket-win",
  description: "দক্ষিণ আফ্রিকার বিপক্ষে ওয়ানডে সিরিজের প্রথম ম্যাচে জয় পেয়েছে বাংলাদেশ নারী ক্রিকেট দল। ৩ উইকেটে জয়ী হয়ে ১-০ ব্যবধানে সিরিজে এগিয়ে আছে বাংলাদেশ। সালমা খাতুনের অসাধান্ত বোলিং পারফরম্যান্স দলকে জয় এনে দিয়েছে।",
  content: "ম্যাচের বিস্তারিত।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T14:00:00Z",
  updatedAt: "2026-01-02T14:00:00Z",
  featured: false,
  views: 8800,
  tags: ["নারী ক্রিকেট"],
},
{
  id: "36",
  title: "হকিতে জাতীয় দলের প্রস্তুতি",
  slug: "bangladesh-hockey-team-preparation",
  description: "আসন্ন এশিয়ান হকি টুর্নামেন্টকে সামনে রেখে বাংলাদেশ হকি দলের প্রস্তুতি ক্যাম্প শুরু হয়েছে। সাভার হকি স্টেডিয়ামে শুরু হওয়া ক্যাম্পে ৩০ জন খেলোয়াড় অংশ নিচ্ছেন। এক মাসের এই ক্যাম্পে ফিটনেস ও ট্যাকটিক্যাল অনুশীলনের উপর জোর দেওয়া হচ্ছে।",
  content: "দলের প্রস্তুতির খবর।",
  image: "/bangladesh-cricket.jpg",
  thumbnail: "/bangladesh-cricket.jpg",
  category: "খেলা",
  categorySlug: "sports",
  author: "খেলা ডেস্ক",
  publishedAt: "2026-01-02T12:30:00Z",
  updatedAt: "2026-01-02T12:30:00Z",
  featured: false,
  views: 5400,
  tags: ["হকি"],
},

/* ===================== বিনোদন (entertainment) ===================== */
{
  id: "37",
  title: "নতুন বাংলা সিনেমা মুক্তি পাচ্ছে",
  slug: "new-bangla-movie-release-week",
  description: "এই সপ্তাহেই প্রেক্ষাগৃহে মুক্তি পেতে যাচ্ছে নতুন বাংলা সিনেমা 'প্রেমের বন্যা'। শাকিব খান ও অপু বিশ্বাসের জুটিতে নির্মিত এই চলচ্চিত্রটি রোমান্টিক-কমেডি ঘরানার। ইতোমধ্যেই ট্রেইলার মুক্তির পর ব্যাপক সাড়া পেয়েছে ছবিটি।",
  content: "চলচ্চিত্রের কাহিনি ও অভিনয়।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T20:00:00Z",
  updatedAt: "2026-01-02T20:00:00Z",
  featured: true,
  views: 10200,
  tags: ["চলচ্চিত্র"],
},
{
  id: "38",
  title: "ওটিটি প্ল্যাটফর্মে নতুন সিরিজ",
  slug: "new-ott-web-series",
  description: "জনপ্রিয় ওটিটি প্ল্যাটফর্ম চরকিতে নতুন ওয়েব সিরিজ 'অন্তর্জাল' মুক্তি পেয়েছে। অপরাধ-থ্রিলার ঘরানার এই সিরিজে অভিনয় করেছেন জয়া আহসান ও তারিক আনাম খান। প্রথম পর্ব মুক্তির পরই দর্শকদের প্রশংসা কুড়িয়েছে সিরিজটি।",
  content: "সিরিজের গল্প ও অভিনেতা।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T18:30:00Z",
  updatedAt: "2026-01-02T18:30:00Z",
  featured: false,
  views: 8600,
  tags: ["ওটিটি"],
},
{
  id: "39",
  title: "সংগীত জগতে নতুন অ্যালবাম",
  slug: "new-music-album-release",
  description: "জনপ্রিয় শিল্পী জেমসের নতুন অ্যালবাম 'প্রতিধ্বনি' মুক্তি পেয়েছে। এই অ্যালবামে ১০টি নতুন গান রয়েছে, যার মধ্যে ৫টি গানের সুর ও সংগীতায়োজন করেছেন তিনি নিজেই। অ্যালবামটি মুক্তির প্রথম দিনেই রেকর্ড সংখ্যক বার স্ট্রিম হয়েছে।",
  content: "অ্যালবামের গান ও প্রতিক্রিয়া।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T16:00:00Z",
  updatedAt: "2026-01-02T16:00:00Z",
  featured: false,
  views: 7400,
  tags: ["সংগীত"],
},
{
  id: "40",
  title: "নাটকের মঞ্চে নতুন প্রযোজনা",
  slug: "new-stage-drama",
  description: "ঢাকা বিশ্ববিদ্যালয়ের নাট্যকলা বিভাগের প্রযোজনায় নতুন নাটক 'অন্তর্ঘাত' মঞ্চস্থ হয়েছে। সমকালীন সামাজিক সমস্যা নিয়ে রচিত এই নাটকটি ইতোমধ্যেই দর্শকদের প্রশংসা অর্জন করেছে। তরুণ নাট্যকারের লেখা এই নাটকে অভিনয় করেছেন শিক্ষার্থীরা।",
  content: "নাটকের কাহিনি ও শিল্পী।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T14:30:00Z",
  updatedAt: "2026-01-02T14:30:00Z",
  featured: false,
  views: 5300,
  tags: ["নাটক"],
},
{
  id: "41",
  title: "টেলিভিশন শোতে নতুন বিচারক",
  slug: "tv-show-new-judge",
  description: "জনপ্রিয় ট্যালেন্ট হান্ট শো 'বাংলার কণ্ঠ'-এ নতুন বিচারক হিসেবে যুক্ত হয়েছেন খ্যাতিমান সংগীতশিল্পী কুমার বিশ্বজিৎ। তাঁর যোগদানে দর্শকদের মধ্যে ব্যাপক উৎসাহ দেখা গেছে। আগামী সপ্তাহ থেকে নতুন মৌসুমের সম্প্রচার শুরু হবে।",
  content: "শো সংক্রান্ত বিস্তারিত।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T13:00:00Z",
  updatedAt: "2026-01-02T13:00:00Z",
  featured: false,
  views: 6100,
  tags: ["টিভি শো"],
},
{
  id: "42",
  title: "সেলিব্রিটিদের সামাজিক উদ্যোগ",
  slug: "celebrity-social-initiative",
  description: "তীব্র শীতে অসহায় মানুষের পাশে দাঁড়িয়েছেন দেশের শীর্ষস্থানীয় সেলিব্রিটিরা। তারা নিজেদের তহবিল থেকে শীতবস্ত্র বিতরণ করেছেন ঢাকার ফুটপাতের বাসিন্দাদের মধ্যে। এছাড়াও শিশুদের জন্য বিশেষ চিকিৎসা শিবিরও চালু করেছেন তারা।",
  content: "সামাজিক কার্যক্রমের খবর।",
  image: "/bengali-cinema.jpg",
  thumbnail: "/bengali-cinema.jpg",
  category: "বিনোদন",
  categorySlug: "entertainment",
  author: "বিনোদন ডেস্ক",
  publishedAt: "2026-01-02T11:30:00Z",
  updatedAt: "2026-01-02T11:30:00Z",
  featured: false,
  views: 5800,
  tags: ["সেলিব্রিটি"],
},

/* ===================== সারাদেশ (regions) ===================== */
{
  id: "43",
  title: "চট্টগ্রামে নতুন উন্নয়ন প্রকল্প শুরু",
  slug: "chittagong-new-development-project",
  description: "চট্টগ্রামে নতুন একটি বড় উন্নয়ন প্রকল্পের কাজ শুরু হয়েছে। এই প্রকল্পের আওতায় কর্ণফুলী নদীর তীরে আধুনিক বসতি এলাকা গড়ে তোলা হবে। প্রকল্প বাস্তবায়নে ৫০০ কোটি টাকা বরাদ্দ দেওয়া হয়েছে এবং কাজ শেষ হতে সময় লাগবে তিন বছর।",
  content: "প্রকল্পের বিস্তারিত তথ্য।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T20:30:00Z",
  updatedAt: "2026-01-02T20:30:00Z",
  featured: true,
  views: 9200,
  tags: ["চট্টগ্রাম"],
},
{
  id: "44",
  title: "রাজশাহীতে কৃষি উৎপাদন বৃদ্ধি",
  slug: "rajshahi-agriculture-growth",
  description: "রাজশাহী অঞ্চলে ফসলের উৎপাদন গত বছরের তুলনায় ১৫ শতাংশ বৃদ্ধি পেয়েছে। বিশেষ করে আম, লিচু ও ধানে রেকর্ড উৎপাদন হয়েছে। আধুনিক কৃষি প্রযুক্তি ব্যবহার ও সময়মত সার-সেচ প্রদান এই সাফল্যের মূল কারণ বলে কৃষি বিভাগ জানিয়েছে।",
  content: "কৃষি খাতের প্রতিবেদন।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T18:00:00Z",
  updatedAt: "2026-01-02T18:00:00Z",
  featured: false,
  views: 6400,
  tags: ["রাজশাহী"],
},
{
  id: "45",
  title: "সিলেটে পর্যটনের নতুন সম্ভাবনা",
  slug: "sylhet-tourism-potential",
  description: "সিলেটের পর্যটন খাতে নতুন সম্ভাবনার দ্বার উন্মোচিত হয়েছে। হাকালুকি হাওর ও রাতারগুল সুন্দরবনের উন্নয়নে বড় বিনিয়োগ আসছে। নতুন হোটেল ও রিসোর্ট নির্মাণের পাশাপাশি যোগাযোগ ব্যবস্থার উন্নয়নও করা হচ্ছে।",
  content: "পর্যটন উন্নয়নের খবর।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T16:30:00Z",
  updatedAt: "2026-01-02T16:30:00Z",
  featured: false,
  views: 7100,
  tags: ["সিলেট"],
},
{
  id: "46",
  title: "খুলনায় নদী খনন প্রকল্প",
  slug: "khulna-river-dredging-project",
  description: "খুলনা অঞ্চলের নদীগুলো পুনঃখননের জন্য নতুন প্রকল্প হাতে নেওয়া হয়েছে। এই প্রকল্পের আওতায় ভৈরব, রূপসা ও কাজীবাচা নদী খনন করা হবে। নদী খনন সম্পন্ন হলে নৌপরিবহন ব্যবস্থার উন্নতি ঘটবে এবং বন্যার ঝুঁকিও কমবে।",
  content: "প্রকল্পের বিস্তারিত।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T15:00:00Z",
  updatedAt: "2026-01-02T15:00:00Z",
  featured: false,
  views: 5900,
  tags: ["খুলনা"],
},
{
  id: "47",
  title: "বরিশালে বন্যা পরিস্থিতির উন্নতি",
  slug: "barisal-flood-situation-improved",
  description: "বরিশালে বন্যা পরিস্থিতির ব্যাপক উন্নতি হয়েছে। জলাবদ্ধতা কাটাতে পানি নিষ্কাশন ব্যবস্থা জোরদার করা হয়েছে। বন্যার্তদের মধ্যে ত্রাণ বিতরণও চলছে পুরোদমে। স্থানীয় প্রশাসন সব ধরনের সহায়তা প্রদান করছে বলে জানানো হয়েছে।",
  content: "বিস্তারিত পরিস্থিতি প্রতিবেদন।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T13:30:00Z",
  updatedAt: "2026-01-02T13:30:00Z",
  featured: false,
  views: 8200,
  tags: ["বরিশাল"],
},
{
  id: "48",
  title: "রংপুরে নতুন শিল্প অঞ্চল",
  slug: "rangpur-new-industrial-zone",
  description: "রংপুরে নতুন শিল্প অঞ্চল প্রতিষ্ঠার কাজ শুরু হয়েছে। এই শিল্প অঞ্চলে টেক্সটাইল, ফার্মাসিউটিক্যাল ও প্রক্রিয়াজাত খাদ্য শিল্প স্থাপন করা হবে। এতে স্থানীয়ভাবে ১০ হাজার লোকের কর্মসংস্থান সৃষ্টির সম্ভাবনা রয়েছে।",
  content: "শিল্প অঞ্চলের বিস্তারিত।",
  image: "/chittagong-development.jpg",
  thumbnail: "/chittagong-development.jpg",
  category: "সারাদেশ",
  categorySlug: "regions",
  author: "আঞ্চলিক ডেস্ক",
  publishedAt: "2026-01-02T12:00:00Z",
  updatedAt: "2026-01-02T12:00:00Z",
  featured: false,
  views: 6700,
  tags: ["রংপুর"],
},
];


export const sampleVideos: VideoItem[] = [
  {
    id: "1",
    title: "জক্ষম বক্তৃতার অভিযোগ - মুখ খুলেলেন জাবি শিক্ষক",
    thumbnail: "/press-conference-dhaka.jpg",
    videoUrl: "https://example.com/video1",
    description: "গুরুত্বপূর্ণ সাংবাদিক সম্মেলনের ভিডিও রিপোর্ট।",
    duration: "5:23",
    publishedAt: "2026-01-03T14:00:00Z",
    views: 24560,
  },
  {
    id: "2",
    title: '"সবাইকে তো ইঞ্চা থাকে প্রতিটা ফরম্যাট খেলার"',
    thumbnail: "/cricket-interview.jpg",
    videoUrl: "https://example.com/video2",
    description: "ক্রিকেট তারকার একচেটিয়া সাক্ষাৎকার।",
    duration: "4:15",
    publishedAt: "2026-01-03T13:30:00Z",
    views: 18900,
  },
  {
    id: "3",
    title: "সীমানে নীতির রাষ্ট্র দিয়ে পবিত্র উচ্চাকাঙ্ক্ষা",
    thumbnail: "/government-announcement.jpg",
    videoUrl: "https://example.com/video3",
    description: "সরকারি ঘোষণা এবং বিবৃতি।",
    duration: "3:45",
    publishedAt: "2026-01-03T12:00:00Z",
    views: 12340,
  },
  {
    id: "4",
    title: "সীমান নেতৃত্ব বিষয় এ ভিডিও প্রতিক্রিয়া",
    thumbnail: "/political-news.jpg",
    videoUrl: "https://example.com/video4",
    description: "রাজনৈতিক নেতাদের ভিডিও প্রতিক্রিয়া।",
    duration: "6:10",
    publishedAt: "2026-01-02T15:45:00Z",
    views: 15670,
  },
  {
    id: "5",
    title: "দুর্নীতি রোধে ব্যবস্থা নেওয়ার প্রতিশ্রুতি",
    thumbnail: "/anti-corruption.jpg",
    videoUrl: "https://example.com/video5",
    description: "দুর্নীতি বিরোধী অভিযান সম্পর্কে খবর।",
    duration: "4:30",
    publishedAt: "2026-01-02T14:20:00Z",
    views: 21450,
  },
  {
    id: "6",
    title: "প্রাকৃতিক দুর্যোগ প্রতিরোধে নতুন উদ্যোগ",
    thumbnail: "/disaster-management.jpg",
    videoUrl: "https://example.com/video6",
    description: "প্রাকৃতিক দুর্যোগ মোকাবেলার উপায়।",
    duration: "5:50",
    publishedAt: "2026-01-02T13:10:00Z",
    views: 8920,
  },
]
